# CI/CD Pipeline Template - Will be activated in Sprint 4
# GitHub Actions workflow for SenialSOLIDApp

name: SenialSOLID CI/CD Pipeline

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

env:
  PYTHON_VERSION: "3.11"

jobs:
  quality:
    name: Code Quality & Security
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Install dependencies
      run: |
        pip install -r requirements-dev.txt
    - name: Lint with flake8
      run: flake8 . --exit-zero
    - name: Security scan
      run: bandit -r . --exit-zero-on-skipped
      
  build:
    name: Build Package
    runs-on: ubuntu-latest
    needs: quality
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Build
      run: |
        pip install build
        python -m build
        
# TODO: Activate in Sprint 4
# - Add comprehensive testing
# - Add Jira/Confluence integration
# - Add deployment steps